<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * AADE-reported lifecycle history of a δελτίο (§4.1 DeliveryEventType list,
 * returned by GetDeliveryNoteStatus). Distinct from `delivery_marks`, which is
 * the audit of the calls WE made: this table is "what AADE says happened" —
 * including events generated by OTHER actors (the carrier's RegisterTransfer,
 * the recipient's ConfirmOutcome/Rejection) that never went through our app.
 * Re-synced idempotently on every `refreshStatus` (RequestDeliveryNoteStatus),
 * keyed by `dedup_key` (the AADE event MARK when present, else a deterministic
 * type|timestamp|actor hash) so a re-poll never duplicates a row.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('delivery_note_events', function (Blueprint $t) {
            $t->id();
            $t->foreignId('company_id')->constrained()->cascadeOnDelete();
            $t->foreignId('delivery_note_id')->constrained()->cascadeOnDelete();

            $t->unsignedBigInteger('event_mark')->nullable(); // §4.1 mark (AADE event id)
            $t->string('event_type', 30);                     // RegisterTransfer / ConfirmOutcome / Rejection
            $t->dateTime('event_timestamp')->nullable();      // §4.1 eventTimestamp
            $t->string('actor_vat', 20)->nullable();          // §4.1 actorVat (carrier/recipient/issuer)
            $t->json('details')->nullable();                  // transport/outcome/rejection specifics

            // Idempotency anchor: event_mark when present, else hash(type|ts|actor).
            $t->string('dedup_key', 80);

            $t->timestamps();

            $t->unique(['delivery_note_id', 'dedup_key']);
            $t->index(['company_id', 'delivery_note_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('delivery_note_events');
    }
};
