
SET SQL DIALECT 3; 

/* CREATE DATABASE '10.23.22.5:/opt/Data/ekdosi-myip.fdb' PAGE_SIZE 16384 DEFAULT CHARACTER SET WIN1253; */


/*  Generators or sequences */
CREATE GENERATOR GEN_AUTO_INVOICE_LOG_ID;
CREATE GENERATOR GEN_CUSTOMER_ID;
CREATE GENERATOR GEN_DELIVERY_METHOD_ID;
CREATE GENERATOR GEN_DISTRIBUTION_AIM_ID;
CREATE GENERATOR GEN_INVLINES_ID;
CREATE GENERATOR GEN_INVOICE_ID;
CREATE GENERATOR GEN_INVPRLINES_ID;
CREATE GENERATOR GEN_MARK_ID;
CREATE GENERATOR GEN_METRIC_UNITS_ID;
CREATE GENERATOR GEN_PAYMENT_ID;
CREATE GENERATOR GEN_PAYMENT_METHOD_ID;
CREATE GENERATOR GEN_PRODUCT_CATEGORIES_ID;
CREATE GENERATOR GEN_PRODUCT_ID;
CREATE GENERATOR GEN_PROD_PRICE_QTY_ID;
CREATE GENERATOR GEN_REPORTS_ID;
CREATE GENERATOR GEN_REPORT_INPUT_DATA_ID;
CREATE GENERATOR GEN_VARTEXT_ID;
CREATE GENERATOR GEN_VAT_CATEGORY_ID;

/* Domain definitions */
CREATE DOMAIN "256DESC" AS VARCHAR(256);
CREATE DOMAIN BIG_NUMERIC AS NUMERIC(15, 4);
CREATE DOMAIN CURRENCY AS DECIMAL(14, 2);
CREATE DOMAIN DESC120 AS VARCHAR(120);
CREATE DOMAIN DESC60 AS VARCHAR(60);
CREATE DOMAIN DESCRIPTION AS VARCHAR(120);
CREATE DOMAIN DESC_BLOB AS BLOB SUB_TYPE TEXT SEGMENT SIZE 80;
CREATE DOMAIN FNAME AS VARCHAR(256);
CREATE DOMAIN LONG_DESCRIPTION AS VARCHAR(120);
CREATE DOMAIN NOTES2K AS VARCHAR(2000);
CREATE DOMAIN PERCENTAGE AS NUMERIC(18, 2);
CREATE DOMAIN QC_3PRECISION AS NUMERIC(15, 3);
CREATE DOMAIN QUANTITY AS NUMERIC(9, 3);
CREATE DOMAIN SMALL_DESCRIPTION AS VARCHAR(30);
CREATE DOMAIN T_AFM AS VARCHAR(20);
CREATE DOMAIN T_BOOLEAN AS SMALLINT;
CREATE DOMAIN T_DOC AS VARCHAR(15);
CREATE DOMAIN T_VATNO AS VARCHAR(20);
COMMIT WORK;

/* Table: AUTO_INVOICE_LOG, Owner: SYSDBA */
CREATE TABLE AUTO_INVOICE_LOG (LOG_ID INTEGER NOT NULL,
        LOG_TIMESTAMP TIMESTAMP DEFAULT 'now',
        CS_INVID INTEGER,
        LOG_MESSAGE NOTES2K,
CONSTRAINT PK_AUTO_INVOICE_LOG PRIMARY KEY (LOG_ID));

/* Table: CONF_PARAMS, Owner: SYSDBA */
CREATE TABLE CONF_PARAMS (VARNAME DESC60 NOT NULL,
        DATA_INT INTEGER,
        DATA_STRING DESCRIPTION,
        DATA_TIMESTAMP TIMESTAMP,
        DATA_FLOAT FLOAT,
        DATA_NUMERIC QC_3PRECISION,
CONSTRAINT PK_CONF_PARAMS PRIMARY KEY (VARNAME));

/* Table: CUSTCS_LINK, Owner: SYSDBA */
CREATE TABLE CUSTCS_LINK (CUST_ID INTEGER NOT NULL,
        CS_ID INTEGER NOT NULL,
CONSTRAINT PK_CUSTCS_LINK PRIMARY KEY (CS_ID));

/* Table: CUSTOMER, Owner: SYSDBA */
CREATE TABLE CUSTOMER (CUST_ID INTEGER NOT NULL,
        TYPE DESC60,
        AFM T_AFM,
        NAME VARCHAR(50) NOT NULL,
        ADDRESS1 VARCHAR(50),
        ADDRESS2 VARCHAR(50),
        CITY VARCHAR(30),
        POSTCODE VARCHAR(10),
        PHONE1 VARCHAR(30),
        PHONE2 VARCHAR(30),
        FAX VARCHAR(30),
        OCCUPATION DESCRIPTION,
        TAXOFFICE VARCHAR(30),
        DETAILS BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        DISCOUNT PERCENTAGE DEFAULT 0,
        EMAIL DESCRIPTION,
        "ORDER" INTEGER,
        COUNTRY VARCHAR(40),
        ALT_CUSTID INTEGER,
        PAYMETH_ID INTEGER,
        VAT_VIES SMALL_DESCRIPTION,
        SECONDARY_EMAIL DESCRIPTION,
        WITHHOLD_TAX INTEGER,
CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUST_ID));

/* Table: CUSTOMER_CS_ACCEPTED, Owner: SYSDBA */
CREATE TABLE CUSTOMER_CS_ACCEPTED (CUST_ID INTEGER NOT NULL,
        AFM T_AFM,
        NAME VARCHAR(120) NOT NULL,
        ADDRESS1 VARCHAR(50),
        ADDRESS2 VARCHAR(50),
        CITY VARCHAR(30),
        POSTCODE VARCHAR(10),
        PHONE1 VARCHAR(30),
        PHONE2 VARCHAR(30),
        FAX VARCHAR(30),
        OCCUPATION DESCRIPTION,
        TAXOFFICE VARCHAR(30),
        DETAILS BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        DISCOUNT PERCENTAGE DEFAULT 0,
        EMAIL DESCRIPTION,
        COUNTRY VARCHAR(40),
        ALT_CUSTID INTEGER,
        PAYMETH_ID INTEGER,
        VAT_VIES SMALL_DESCRIPTION,
        SECONDARY_EMAIL DESCRIPTION,
CONSTRAINT PK_CUSTOMER_CS_ACCEPTED PRIMARY KEY (CUST_ID));

/* Table: DELIVERY_METHOD, Owner: SYSDBA */
CREATE TABLE DELIVERY_METHOD (METHOD_ID INTEGER NOT NULL,
        DESCRIPTION DESCRIPTION,
CONSTRAINT PK_DELIVERY_METHOD PRIMARY KEY (METHOD_ID));

/* Table: DISTRIBUTION_AIM, Owner: SYSDBA */
CREATE TABLE DISTRIBUTION_AIM (DISTAIM_ID INTEGER NOT NULL,
        DESCRIPTION DESCRIPTION,
CONSTRAINT PK_DISTRIBUTION_AIM PRIMARY KEY (DISTAIM_ID));

/* Table: INVLINES, Owner: SYSDBA */
CREATE TABLE INVLINES (INVLINE_ID INTEGER NOT NULL,
        INVOICE_ID INTEGER,
        PRODUCT_ID INTEGER,
        QTY NUMERIC(9, 3) DEFAULT 1,
        PRICE_PER_ITEM CURRENCY,
        DISCOUNT BIG_NUMERIC DEFAULT 0,
        VATPERCENT PERCENTAGE,
        PRICE CURRENCY,
        PRICEWVAT CURRENCY,
        PRODUCT_DESCR "256DESC",
        METRIC_UNIT VARCHAR(15),
        NOTES NOTES2K,
CONSTRAINT PK_INVLINES PRIMARY KEY (INVLINE_ID));

/* Table: INVOICE, Owner: SYSDBA */
CREATE TABLE INVOICE (INVOICE_ID INTEGER NOT NULL,
        INVCODE VARCHAR(15) NOT NULL,
        CUST_ID INTEGER,
        CODE INTEGER,
        INVTYPE VARCHAR(6),
        INVDATE DATE DEFAULT 'NOW',
        MAILED SMALLINT DEFAULT 0,
        PRINTED T_BOOLEAN DEFAULT 0,
        DELIVERYDATE DATE,
        DISTRAIM_ID INTEGER,
        DELMETHOD_ID INTEGER,
        PAYMETH_ID INTEGER,
        DISCOUNT CURRENCY DEFAULT 0,
        PRICE CURRENCY,
        PRICEWVAT CURRENCY,
        NOTES_OLD BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        CONV_INVOICE_ID INTEGER,
        INVTIME TIME DEFAULT 'NOW',
        ADDRESS1 VARCHAR(50),
        ADDRESS2 VARCHAR(50),
        CITY VARCHAR(40),
        POSTCODE VARCHAR(10),
        COUNTRY VARCHAR(40),
        NOTES NOTES2K,
        MYDATA_SENT SMALLINT,
        COMPANY_NAME LONG_DESCRIPTION,
        VAT_NO T_AFM,
        VIES_VAT T_AFM,
        OCCUPATION LONG_DESCRIPTION,
        EMAIL_SENT LONG_DESCRIPTION,
        WITHHOLD_AMOUNT CURRENCY,
        MYDATA_STATE SMALL_DESCRIPTION,
        MYDATA_MARK DESC120,
        MYDATA_URL VARCHAR(1500),
CONSTRAINT PK_INVOICE PRIMARY KEY (INVOICE_ID),
CONSTRAINT UNQ1_INVOICE UNIQUE (INVCODE));

/* Table: INVTYPE, Owner: SYSDBA */
CREATE TABLE INVTYPE (INVTYPE_ID VARCHAR(6) NOT NULL,
        NAME DESCRIPTION NOT NULL,
        FRM_FILENAME VARCHAR(256),
        EAFDSS_SCRIPT VARCHAR(20),
        INVCOUNT INTEGER DEFAULT 1,
        SHOW_ON_MENU SMALLINT,
        PRINTER_NAME VARCHAR(256),
        PRINTER_NO SMALLINT,
        DISTAIM_ID INTEGER,
        DELIVERYMETHOD_ID INTEGER,
        PAYMETH_ID INTEGER,
        CUST_ID INTEGER,
        CREDITINVOICE T_BOOLEAN,
        RETURNINVOICE T_BOOLEAN,
        MYDATA_TYPE VARCHAR(5),
        MYDATA_INCOME_CLASS SMALL_DESCRIPTION,
        MYDATA_INCOME_CLASS_CATEGORY SMALL_DESCRIPTION,
CONSTRAINT PK_INVTYPE PRIMARY KEY (INVTYPE_ID));

/* Table: MARK, Owner: SYSDBA */
CREATE TABLE MARK (ID INTEGER NOT NULL,
        MARK VARCHAR(50) NOT NULL,
        INVOICE_ID INTEGER,
        RESPONSE VARCHAR(32762),
        "DATE" DATE DEFAULT 'NOW',
        "TIME" TIMESTAMP DEFAULT 'NOW',
        MYDATA_ACTION SMALL_DESCRIPTION,
        REQUEST VARCHAR(17000),
        INVOICE_URL VARCHAR(1500),
CONSTRAINT PK_MARK PRIMARY KEY (ID));

/* Table: METRIC_UNITS, Owner: SYSDBA */
CREATE TABLE METRIC_UNITS (METRIC_ID INTEGER NOT NULL,
        NAME VARCHAR(15),
        NOTES DESC_BLOB,
CONSTRAINT PK_METRIC_UNITS PRIMARY KEY (METRIC_ID));

/* Table: PAYMENT, Owner: SYSDBA */
CREATE TABLE PAYMENT (PAYMENT_ID INTEGER NOT NULL,
        CUST_ID INTEGER,
        PAY_DATE DATE,
        "VALUE" CURRENCY,
        NOTES DESC_BLOB,
CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_ID));

/* Table: PAYMENT_METHOD, Owner: SYSDBA */
CREATE TABLE PAYMENT_METHOD (METHOD_ID INTEGER NOT NULL,
        DESCRIPTION DESCRIPTION,
        DUE_DAYS INTEGER,
CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY (METHOD_ID));

/* Table: PRODUCT, Owner: SYSDBA */
CREATE TABLE PRODUCT (PRODUCT_ID INTEGER NOT NULL,
        BARCODE VARCHAR(25),
        DESCRIPTION_SHORT DESCRIPTION NOT NULL,
        CAT_ID INTEGER NOT NULL,
        VATCAT_ID INTEGER NOT NULL,
        BUY_PRICE CURRENCY DEFAULT 0,
        SELL_PRICE CURRENCY DEFAULT 0,
        PRICE_WVAT CURRENCY DEFAULT 0,
        DATE_INSERTED DATE DEFAULT 'TODAY',
        RESERVE NUMERIC(4, 3) DEFAULT 0,
        RESERVE_SECURE NUMERIC(4, 3) DEFAULT 0,
        DESCRIPTION DESC_BLOB,
        METRIC_ID INTEGER,
        LAST_UPDATE TIMESTAMP DEFAULT 'NOW',
CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
CONSTRAINT UNQ1_PRODUCT UNIQUE (BARCODE));

/* Table: PRODUCT_CATEGORIES, Owner: SYSDBA */
CREATE TABLE PRODUCT_CATEGORIES (CAT_ID INTEGER NOT NULL,
        DESCRIPTION_SHORT DESCRIPTION NOT NULL,
        DESCRIPTION BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        MARKUP CURRENCY,
CONSTRAINT PK_PRODUCT_CATEGORIES PRIMARY KEY (CAT_ID));

/* Table: PROD_PRICE_QTY, Owner: SYSDBA */
CREATE TABLE PROD_PRICE_QTY (PROD_PRICE_ID INTEGER NOT NULL,
        PRODUCT_ID INTEGER NOT NULL,
        VAL CURRENCY,
        DISCOUNT_PERCENT PERCENTAGE,
        QTY QUANTITY,
CONSTRAINT PK_PROD_PRICE_QTY PRIMARY KEY (PROD_PRICE_ID));

/* Table: REPORTS, Owner: SYSDBA */
CREATE TABLE REPORTS (REPORT_ID INTEGER NOT NULL,
        DESCRIPTION DESCRIPTION,
        NOTES DESC_BLOB,
        FILENAME FNAME,
        SHOW_ON_MENU T_BOOLEAN,
CONSTRAINT PK_REPORTS PRIMARY KEY (REPORT_ID));

/* Table: REPORT_INPUT_DATA, Owner: SYSDBA */
CREATE TABLE REPORT_INPUT_DATA (INPUTDATA_ID INTEGER NOT NULL,
        REPORT_ID INTEGER NOT NULL,
        VARIABLE_NAME LONG_DESCRIPTION,
        VAL LONG_DESCRIPTION,
        DESCRIPTION DESCRIPTION,
CONSTRAINT PK_REPORT_INPUT_DATA PRIMARY KEY (INPUTDATA_ID));

/* Table: RETURN_INVOICE_EXTRAS, Owner: SYSDBA */
CREATE TABLE RETURN_INVOICE_EXTRAS (QTY_GIVEN QUANTITY,
        QTY_RETURNED QUANTITY,
        INVLINE_ID INTEGER NOT NULL,
        QTY_SENT QUANTITY,
CONSTRAINT PK_RETURN_INVOICE_EXTRAS PRIMARY KEY (INVLINE_ID));

/* Table: VARTEXT, Owner: SYSDBA */
CREATE TABLE VARTEXT (VARTEXT_ID INTEGER NOT NULL,
        DESCRIPTION DESCRIPTION,
        "GROUP" INTEGER,
CONSTRAINT PK_VARTEXT PRIMARY KEY (VARTEXT_ID));

/* Table: VAT_CATEGORY, Owner: SYSDBA */
CREATE TABLE VAT_CATEGORY (VATCAT_ID INTEGER NOT NULL,
        DESCRIPTION DESCRIPTION,
        "VALUE" NUMERIC(15, 2) DEFAULT 0.0,
        LONG_DESCRIPTION DESC_BLOB,
        DEFAULT_CAT T_BOOLEAN DEFAULT 0,
CONSTRAINT PK_VAT_CATEGORY PRIMARY KEY (VATCAT_ID));

/*  External Function declarations */
DECLARE EXTERNAL FUNCTION "lpad"
CSTRING(255) CHARACTER SET WIN1253, INTEGER, CSTRING(1) CHARACTER SET WIN1253
RETURNS CSTRING(255) CHARACTER SET WIN1253 FREE_IT
ENTRY_POINT 'IB_UDF_lpad' MODULE_NAME 'ib_udf';


COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures headers */
CREATE OR ALTER PROCEDURE CALCULATE_INVOICE_VALUES (INVOICE_ID INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE CALCULATE_VAT_FOR_INVOICE (INVOICE_ID INTEGER)
RETURNS (VAT_PERCENT PERCENTAGE,
VAL CURRENCY)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE CHECK_PROD_AVAILABILITY (XPRODUCT_ID INTEGER,
SDAP_INVOICE_ID INTEGER)
RETURNS (QTY QUANTITY)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE CREATE_RETURN_INVOICE (SDEP_INV_ID INTEGER,
INVDATE DATE,
INVTIME TIME)
RETURNS (INVOICE_ID INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE FILL_PRDESCR_INVLINES AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE GET_ALL_CUSTOMERS_BALANCE RETURNS (CUSTOMER_ID INTEGER,
BALANCE CURRENCY)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_COMB_CUSTOMER_INVTYPES (START_DATE DATE,
END_DATE DATE,
AFM VARCHAR(50) CHARACTER SET WIN1253)
RETURNS (CUST_NAME VARCHAR(80) CHARACTER SET WIN1253,
VAT_NO VARCHAR(50) CHARACTER SET WIN1253,
INVCODE VARCHAR(20) CHARACTER SET WIN1253,
INVTYPE VARCHAR(30) CHARACTER SET WIN1253,
NET_PRICE NUMERIC(15, 2),
VAT_PRICE NUMERIC(15, 2),
SHOP_INVOICE_ID INTEGER,
CAR_INVOICE_ID INTEGER)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_COMB_INVLINES (SHOP_INVOICE_ID INTEGER,
CAR_INVOICE_ID INTEGER)
RETURNS (PRODUCT_DESCR VARCHAR(120) CHARACTER SET WIN1253,
QTY NUMERIC(15, 3),
PRICE_PER_ITEM NUMERIC(15, 2),
VATPERCENT NUMERIC(8, 2),
PRICE NUMERIC(15, 2),
PRICEWVAT NUMERIC(15, 2))
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_COMB_INVOICES_CUSTOMERS (START_DATE DATE,
END_DATE DATE)
RETURNS (CUST_NAME VARCHAR(80) CHARACTER SET WIN1253,
VAT_NO VARCHAR(50) CHARACTER SET WIN1253,
INVCODE VARCHAR(20) CHARACTER SET WIN1253,
INVTYPE VARCHAR(30) CHARACTER SET WIN1253,
NET_PRICE NUMERIC(15, 2),
VAT_PRICE NUMERIC(15, 2))
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_CUSTOMER_BALANCE (XCUST_ID INTEGER)
RETURNS (BALANCE CURRENCY)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE GET_INV_CODE (XINVTYPE VARCHAR(6) CHARACTER SET WIN1253)
RETURNS (INV_CNTCODE VARCHAR(15) CHARACTER SET WIN1253)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE INSPECT_CUST_ORDER AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE LZ_PAD (XNUMBER INTEGER,
XDIGITS INTEGER)
RETURNS (NUM VARCHAR(20) CHARACTER SET WIN1253)
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE MYDATA_EXTRACT_ALL_URLS AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE MYDATA_EXTRACT_URL (MARK_TABLE_ID INTEGER)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE SHOW_CUMULATIVE_INVOICE (INVOICEID INTEGER)
RETURNS (PRODUCT_ID INTEGER,
INVOICE_ID INTEGER,
BARCODE INTEGER,
DESCRIPTION_SHORT DESCRIPTION,
QTY NUMERIC(9, 3))
AS 
BEGIN SUSPEND; END ^
CREATE OR ALTER PROCEDURE SWAP_CUST_ORDER (CUST_ID1 INTEGER,
CUST_ID2 INTEGER)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE UPDATE_CS_CUST_CONNECTION (XCS_ID INTEGER,
XCUST_ID INTEGER)
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE UPDATE_ROWS_CINVOICE (XPRODUCT_ID INTEGER,
XINVOICE_ID INTEGER,
XQTY NUMERIC(9, 3))
AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE YIELD_RETINV_STATS (SDEP_ID INTEGER)
RETURNS (INVTYPE_ID VARCHAR(6) CHARACTER SET WIN1253,
INVCODE_START VARCHAR(15) CHARACTER SET WIN1253,
INVCODE_END VARCHAR(15) CHARACTER SET WIN1253,
TOTAL_TRANSACTIONS CURRENCY)
AS 
BEGIN SUSPEND; END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

/*  Index definitions for all user tables */
CREATE DESCENDING INDEX PAYMENT_METHOD_IDX1 ON PAYMENT_METHOD (DUE_DAYS);

ALTER TABLE CUSTCS_LINK ADD CONSTRAINT FK_CUSTCS_LINK_1 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CUSTOMER ADD CONSTRAINT FK_CUSTOMER_1 FOREIGN KEY (PAYMETH_ID) REFERENCES PAYMENT_METHOD (METHOD_ID) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE INVLINES ADD CONSTRAINT FK_INVLINES_1 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE INVLINES ADD CONSTRAINT FK_INVLINES_2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);

ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_1 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID);

ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_2 FOREIGN KEY (INVTYPE) REFERENCES INVTYPE (INVTYPE_ID);

ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_3 FOREIGN KEY (DISTRAIM_ID) REFERENCES DISTRIBUTION_AIM (DISTAIM_ID);

ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_4 FOREIGN KEY (DELMETHOD_ID) REFERENCES DELIVERY_METHOD (METHOD_ID);

ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_5 FOREIGN KEY (PAYMETH_ID) REFERENCES PAYMENT_METHOD (METHOD_ID);

ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_6 FOREIGN KEY (CONV_INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);

ALTER TABLE INVTYPE ADD CONSTRAINT FK_INVTYPE_1 FOREIGN KEY (DISTAIM_ID) REFERENCES DISTRIBUTION_AIM (DISTAIM_ID) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE INVTYPE ADD CONSTRAINT FK_INVTYPE_2 FOREIGN KEY (DELIVERYMETHOD_ID) REFERENCES DELIVERY_METHOD (METHOD_ID) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE INVTYPE ADD CONSTRAINT FK_INVTYPE_3 FOREIGN KEY (PAYMETH_ID) REFERENCES PAYMENT_METHOD (METHOD_ID) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE INVTYPE ADD CONSTRAINT FK_INVTYPE_4 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE MARK ADD CONSTRAINT FK_MARK_1 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_1 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_1 FOREIGN KEY (CAT_ID) REFERENCES PRODUCT_CATEGORIES (CAT_ID);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_2 FOREIGN KEY (VATCAT_ID) REFERENCES VAT_CATEGORY (VATCAT_ID);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_3 FOREIGN KEY (METRIC_ID) REFERENCES METRIC_UNITS (METRIC_ID);

ALTER TABLE PROD_PRICE_QTY ADD CONSTRAINT FK_PROD_PRICE_QTY_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE REPORT_INPUT_DATA ADD CONSTRAINT FK_REPORT_INPUT_DATA_1 FOREIGN KEY (REPORT_ID) REFERENCES REPORTS (REPORT_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE RETURN_INVOICE_EXTRAS ADD CONSTRAINT FK_RETURN_INVOICE_EXTRAS_1 FOREIGN KEY (INVLINE_ID) REFERENCES INVLINES (INVLINE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures bodies */

ALTER PROCEDURE CALCULATE_INVOICE_VALUES (INVOICE_ID INTEGER)
AS 
DECLARE VARIABLE PRICE_VAL NUMERIC(18,2);
DECLARE VARIABLE PRICEWVAT_VAL NUMERIC(18,2);
begin
  SELECT SUM(PRICE), SUM(PRICEWVAT) FROM INVLINES WHERE INVOICE_ID = :INVOICE_ID INTO :PRICE_VAL, :PRICEWVAT_VAL;

  UPDATE INVOICE SET PRICE = :PRICE_VAL, PRICEWVAT = :PRICEWVAT_VAL WHERE INVOICE_ID = :INVOICE_ID;
  suspend;
end ^

ALTER PROCEDURE CALCULATE_VAT_FOR_INVOICE (INVOICE_ID INTEGER)
RETURNS (VAT_PERCENT PERCENTAGE,
VAL CURRENCY)
AS 
begin
 FOR
  SELECT VATPERCENT, SUM((INVLINES.PRICEWVAT - INVLINES.PRICE)- ((INVLINES.PRICEWVAT - INVLINES.PRICE) * (CAST(INVOICE.DISCOUNT AS NUMERIC(14,4))/100) ) ) FROM INVLINES
   INNER JOIN INVOICE ON INVLINES.INVOICE_ID = INVOICE.INVOICE_ID
   WHERE INVLINES.INVOICE_ID = :INVOICE_ID
   GROUP BY VATPERCENT
   INTO :VAT_PERCENT, :VAL DO
  suspend;
end ^

ALTER PROCEDURE CHECK_PROD_AVAILABILITY (XPRODUCT_ID INTEGER,
SDAP_INVOICE_ID INTEGER)
RETURNS (QTY QUANTITY)
AS 
 ^

ALTER PROCEDURE CREATE_RETURN_INVOICE (SDEP_INV_ID INTEGER,
INVDATE DATE,
INVTIME TIME)
RETURNS (INVOICE_ID INTEGER)
AS 
 ^

ALTER PROCEDURE FILL_PRDESCR_INVLINES AS 
declare variable ID INTEGER;
declare variable PR_ID INTEGER;
declare variable METRIC_ID INTEGER;
declare variable DESCR VARCHAR(120);
begin

 FOR SELECT INVLINE_ID, PRODUCT_ID FROM INVLINES INTO :ID, :PR_ID DO
 BEGIN
  SELECT PRODUCT.DESCRIPTION_SHORT, METRIC_ID FROM PRODUCT WHERE PRODUCT_ID = :PR_ID INTO :DESCR, :METRIC_ID;
   UPDATE INVLINES SET PRODUCT_DESCR = :DESCR WHERE INVLINE_ID = :ID;

   UPDATE INVLINES SET METRIC_UNIT = (SELECT NAME FROM METRIC_UNITS WHERE METRIC_ID = :METRIC_ID) WHERE INVLINE_ID = :ID;
 END
end ^

ALTER PROCEDURE GET_ALL_CUSTOMERS_BALANCE RETURNS (CUSTOMER_ID INTEGER,
BALANCE CURRENCY)
AS 
begin
  FOR SELECT CUST_ID FROM CUSTOMER INTO :CUSTOMER_ID DO
  BEGIN
   SELECT BALANCE FROM GET_CUSTOMER_BALANCE(:CUSTOMER_ID) INTO :BALANCE;
    suspend;
  END


end ^

ALTER PROCEDURE GET_COMB_CUSTOMER_INVTYPES (START_DATE DATE,
END_DATE DATE,
AFM VARCHAR(50) CHARACTER SET WIN1253)
RETURNS (CUST_NAME VARCHAR(80) CHARACTER SET WIN1253,
VAT_NO VARCHAR(50) CHARACTER SET WIN1253,
INVCODE VARCHAR(20) CHARACTER SET WIN1253,
INVTYPE VARCHAR(30) CHARACTER SET WIN1253,
NET_PRICE NUMERIC(15, 2),
VAT_PRICE NUMERIC(15, 2),
SHOP_INVOICE_ID INTEGER,
CAR_INVOICE_ID INTEGER)
AS 
DECLARE VARIABLE TMP_CUST_NAME VARCHAR(80);
begin
  FOR SELECT INVOICE_ID, CUSTOMER.NAME, AFM, INVCODE,  INVTYPE, INVOICE.PRICE AS NET_PRICE, (INVOICE.PRICEWVAT - INVOICE.PRICE) AS VAT_PRICE
    FROM INVOICE LEFT OUTER JOIN CUSTOMER ON INVOICE.CUST_ID = CUSTOMER.CUST_ID
    WHERE CUSTOMER.AFM = :AFM AND INVDATE BETWEEN :START_DATE AND :END_DATE
    INTO :SHOP_INVOICE_ID, :CUST_NAME, :VAT_NO, :INVCODE, :INVTYPE, :NET_PRICE, :VAT_PRICE DO
  BEGIN
   suspend;
  END

  SHOP_INVOICE_ID = NULL;

 FOR EXECUTE STATEMENT ('SELECT INVOICE_ID, CUSTOMER.NAME, AFM, INVCODE, INVTYPE, INVOICE.PRICE AS NET_PRICE, (INVOICE.PRICEWVAT - INVOICE.PRICE) AS VAT_PRICE
    FROM INVOICE LEFT OUTER JOIN CUSTOMER ON INVOICE.CUST_ID = CUSTOMER.CUST_ID
    WHERE AFM = ? AND INVDATE BETWEEN ? AND ?') (:AFM, :START_DATE, :END_DATE)
    ON EXTERNAL 'C:\Users\haris\Desktop\Deployment\ekdosi-arif-rossidis\ekdosi.fdb'
    AS USER 'SYSDBA'
    PASSWORD 'masterkey'
    INTO :CAR_INVOICE_ID, :CUST_NAME, :VAT_NO, :INVCODE, :INVTYPE, :NET_PRICE, :VAT_PRICE DO
  BEGIN
  SELECT FIRST 1 CUSTOMER.NAME FROM CUSTOMER WHERE AFM = :VAT_NO INTO :CUST_NAME;
  SUSPEND;
  END
end ^

ALTER PROCEDURE GET_COMB_INVLINES (SHOP_INVOICE_ID INTEGER,
CAR_INVOICE_ID INTEGER)
RETURNS (PRODUCT_DESCR VARCHAR(120) CHARACTER SET WIN1253,
QTY NUMERIC(15, 3),
PRICE_PER_ITEM NUMERIC(15, 2),
VATPERCENT NUMERIC(8, 2),
PRICE NUMERIC(15, 2),
PRICEWVAT NUMERIC(15, 2))
AS 
begin
  IF(SHOP_INVOICE_ID IS NOT NULL) THEN
  BEGIN
   FOR SELECT PRODUCT.DESCRIPTION_SHORT, QTY, VATPERCENT, PRICE_PER_ITEM, PRICE, PRICEWVAT FROM INVLINES
                LEFT OUTER JOIN PRODUCT ON INVLINES.PRODUCT_ID = PRODUCT.PRODUCT_ID
                WHERE INVOICE_ID = :SHOP_INVOICE_ID
            INTO :PRODUCT_DESCR, :QTY, :VATPERCENT, :PRICE_PER_ITEM, :PRICE, :PRICEWVAT DO
   BEGIN
    SUSPEND;
   END
  END

  IF(CAR_INVOICE_ID IS NOT NULL) THEN
  BEGIN
   FOR EXECUTE STATEMENT ('SELECT PRODUCT.DESCRIPTION_SHORT, QTY, VATPERCENT, PRICE_PER_ITEM, PRICE, PRICEWVAT FROM INVLINES
                                LEFT OUTER JOIN PRODUCT ON INVLINES.PRODUCT_ID = PRODUCT.PRODUCT_ID
                WHERE INVOICE_ID = ?')(CAR_INVOICE_ID)
   ON EXTERNAL 'C:\Users\haris\Desktop\Deployment\ekdosi-arif-rossidis\ekdosi.fdb'
    AS USER 'SYSDBA'
    PASSWORD 'masterkey'
   INTO :PRODUCT_DESCR, :QTY, :VATPERCENT, :PRICE_PER_ITEM, :PRICE, :PRICEWVAT DO
   BEGIN
    SUSPEND;
   END
  END
end ^

ALTER PROCEDURE GET_COMB_INVOICES_CUSTOMERS (START_DATE DATE,
END_DATE DATE)
RETURNS (CUST_NAME VARCHAR(80) CHARACTER SET WIN1253,
VAT_NO VARCHAR(50) CHARACTER SET WIN1253,
INVCODE VARCHAR(20) CHARACTER SET WIN1253,
INVTYPE VARCHAR(30) CHARACTER SET WIN1253,
NET_PRICE NUMERIC(15, 2),
VAT_PRICE NUMERIC(15, 2))
AS 
DECLARE VARIABLE TMP_CUST_NAME VARCHAR(80);
begin
  FOR SELECT CUSTOMER.NAME, AFM, INVCODE,  INVTYPE, INVOICE.PRICE AS NET_PRICE, (INVOICE.PRICEWVAT - INVOICE.PRICE) AS VAT_PRICE
    FROM INVOICE LEFT OUTER JOIN CUSTOMER ON INVOICE.CUST_ID = CUSTOMER.CUST_ID
    WHERE INVDATE BETWEEN :START_DATE AND :END_DATE
    INTO :CUST_NAME, :VAT_NO, :INVCODE, :INVTYPE, :NET_PRICE, :VAT_PRICE DO
  BEGIN
   suspend;
  END


 FOR EXECUTE STATEMENT ('SELECT CUSTOMER.NAME, AFM, INVCODE, INVTYPE, INVOICE.PRICE AS NET_PRICE, (INVOICE.PRICEWVAT - INVOICE.PRICE) AS VAT_PRICE
    FROM INVOICE LEFT OUTER JOIN CUSTOMER ON INVOICE.CUST_ID = CUSTOMER.CUST_ID
    WHERE AFM IS NOT NULL AND INVDATE BETWEEN ? AND ?') ( :START_DATE, :END_DATE)
    ON EXTERNAL 'C:\Users\haris\Desktop\Deployment\ekdosi-arif-rossidis\ekdosi.fdb'
    AS USER 'SYSDBA'
    PASSWORD 'masterkey'
    INTO :CUST_NAME, :VAT_NO, :INVCODE, :INVTYPE, :NET_PRICE, :VAT_PRICE DO
  BEGIN
  SELECT FIRST 1 CUSTOMER.NAME FROM CUSTOMER WHERE AFM = :VAT_NO INTO :CUST_NAME;
  SUSPEND;
  END
end ^

ALTER PROCEDURE GET_CUSTOMER_BALANCE (XCUST_ID INTEGER)
RETURNS (BALANCE CURRENCY)
AS 
declare variable TOTAL CURRENCY;
declare variable PAID CURRENCY;
begin
  SELECT COALESCE(SUM(INVOICE.PRICEWVAT),0) FROM INVOICE
    LEFT OUTER JOIN PAYMENT_METHOD ON INVOICE.PAYMETH_ID = PAYMENT_METHOD.METHOD_ID WHERE INVOICE.CUST_ID = :XCUST_ID AND DUE_DAYS > 0 INTO total;
  SELECT COALESCE(SUM(PAYMENT."VALUE"),0) FROM PAYMENT WHERE PAYMENT.CUST_ID = :XCUST_ID INTO paid;


  BALANCE = total - paid;

  suspend;
end ^

ALTER PROCEDURE GET_INV_CODE (XINVTYPE VARCHAR(6) CHARACTER SET WIN1253)
RETURNS (INV_CNTCODE VARCHAR(15) CHARACTER SET WIN1253)
AS 
declare variable CNT INTEGER;
begin
  SELECT INVTYPE.INVCOUNT FROM INVTYPE WHERE INVTYPE.INVTYPE_ID = :XINVTYPE
  INTO :CNT;

  INV_CNTCODE = XINVTYPE || CNT;
  suspend;
end ^

ALTER PROCEDURE INSPECT_CUST_ORDER AS 
declare variable CUST_ID INTEGER;
declare variable CUST_ORDER INTEGER;
declare variable ORDR INTEGER;
begin
  FOR SELECT CUST_ID FROM CUSTOMER WHERE "ORDER" IS NULL INTO :CUST_ID  DO
  BEGIN
  SELECT COALESCE(MAX("ORDER"),0)+1 FROM CUSTOMER INTO ORDR;
  UPDATE CUSTOMER SET "ORDER" = :ORDR WHERE CUST_ID = :CUST_ID;
  END

  ORDR = 1;
  FOR SELECT CUST_ID, "ORDER" FROM CUSTOMER ORDER BY "ORDER" INTO CUST_ID, CUST_ORDER DO
  BEGIN
   IF (:CUST_ORDER != :ORDR) THEN
   BEGIN
    UPDATE CUSTOMER SET "ORDER" = :ORDR WHERE CUST_ID = :CUST_ID;
   END
  ORDR = ORDR +1;
  END

end ^

ALTER PROCEDURE LZ_PAD (XNUMBER INTEGER,
XDIGITS INTEGER)
RETURNS (NUM VARCHAR(20) CHARACTER SET WIN1253)
AS 
begin
  NUM = CAST(XNUMBER AS VARCHAR(20));
  NUM = lpad(:NUM, XDIGITS, '0');
  suspend;
end ^

ALTER PROCEDURE MYDATA_EXTRACT_ALL_URLS AS 
DECLARE VARIABLE MARK_TABLE_ID INTEGER;
begin
  FOR SELECT ID FROM MARK WHERE ID > 2050 AND INVOICE_URL IS NULL ORDER BY "ID" ASC INTO :MARK_TABLE_ID DO
  BEGIN
  EXECUTE PROCEDURE MYDATA_EXTRACT_URL(:MARK_TABLE_ID);
  END
  suspend;
end ^

ALTER PROCEDURE MYDATA_EXTRACT_URL (MARK_TABLE_ID INTEGER)
AS 
DECLARE VARIABLE RESPONSE VARCHAR(30000);
DECLARE VARIABLE "MARK" VARCHAR(120);
DECLARE VARIABLE MYDATA_ACTION VARCHAR(120);
DECLARE VARIABLE INVOICE_ID INTEGER;
DECLARE VARIABLE MARK_URL VARCHAR(1500);

DECLARE VARIABLE QR_START INTEGER;
DECLARE VARIABLE QR_END INTEGER;
begin
 SELECT "MARK", RESPONSE, MYDATA_ACTION, INVOICE_ID, INVOICE_URL FROM MARK WHERE ID = :MARK_TABLE_ID ORDER BY ID ASC
                INTO :MARK, :RESPONSE, :MYDATA_ACTION, :INVOICE_ID, :MARK_URL;

 IF(MYDATA_ACTION = 'CANCEL') THEN
 BEGIN

  UPDATE MARK SET INVOICE_URL = '' WHERE ID = :MARK_TABLE_ID;
 END

 QR_START = POSITION('<qrUrl>' IN RESPONSE);
 QR_END = POSITION('</qrUrl>' IN RESPONSE);
 IF(QR_START != -1 OR QR_END != -1) THEN
 BEGIN
  MARK_URL = SUBSTRING(RESPONSE FROM :QR_START+7 FOR (QR_END - QR_START-7));
  UPDATE MARK SET INVOICE_URL = :MARK_URL WHERE ID = :MARK_TABLE_ID;
 END


end ^

ALTER PROCEDURE SHOW_CUMULATIVE_INVOICE (INVOICEID INTEGER)
RETURNS (PRODUCT_ID INTEGER,
INVOICE_ID INTEGER,
BARCODE INTEGER,
DESCRIPTION_SHORT DESCRIPTION,
QTY NUMERIC(9, 3))
AS 
begin
 INVOICE_ID = :INVOICEID;

 if(:INVOICEID IS NULL) THEN
 BEGIN
 FOR SELECT A.PRODUCT_ID, CAST(A.BARCODE AS INTEGER) AS BARCODE, A.DESCRIPTION_SHORT, 0 AS QTY
 FROM PRODUCT A
WHERE PRODUCT_ID NOT IN
 (SELECT PRODUCT_ID FROM INVLINES WHERE PRODUCT_ID = A.PRODUCT_ID AND
INVOICE_ID IS NULL)
ORDER BY BARCODE INTO :PRODUCT_ID, :BARCODE,:DESCRIPTION_SHORT, :QTY do
suspend;

FOR SELECT C.PRODUCT_ID, CAST(C.BARCODE AS INTEGER) AS BARCODE, C.DESCRIPTION_SHORT, B.QTY
 FROM INVLINES B INNER JOIN PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID WHERE B.INVOICE_ID IS NULL INTO :PRODUCT_ID,:BARCODE,:DESCRIPTION_SHORT, :QTY DO
suspend;
 end
 ELSE
 BEGIN
 FOR SELECT A.PRODUCT_ID, CAST(A.BARCODE AS INTEGER) AS BARCODE, A.DESCRIPTION_SHORT, 0 AS QTY
 FROM PRODUCT A
WHERE PRODUCT_ID NOT IN
 (SELECT PRODUCT_ID FROM INVLINES WHERE PRODUCT_ID = A.PRODUCT_ID AND
INVOICE_ID = :INVOICEID)
ORDER BY BARCODE INTO :PRODUCT_ID, :BARCODE,:DESCRIPTION_SHORT, :QTY do
suspend;

FOR SELECT C.PRODUCT_ID, CAST(C.BARCODE AS INTEGER) AS BARCODE, C.DESCRIPTION_SHORT, B.QTY
 FROM INVLINES B INNER JOIN PRODUCT C ON B.PRODUCT_ID = C.PRODUCT_ID WHERE B.INVOICE_ID = :INVOICEID INTO :PRODUCT_ID,:BARCODE,:DESCRIPTION_SHORT, :QTY DO
suspend;
 END
end ^

ALTER PROCEDURE SWAP_CUST_ORDER (CUST_ID1 INTEGER,
CUST_ID2 INTEGER)
AS 
declare variable ORDR1 INTEGER;
declare variable ORDR2 INTEGER;
begin
 SELECT "ORDER" FROM CUSTOMER WHERE CUST_ID = :CUST_ID1 INTO ORDR1;
 SELECT "ORDER" FROM CUSTOMER WHERE CUST_ID = :CUST_ID2 INTO ORDR2;

 UPDATE CUSTOMER SET "ORDER" = :ORDR2 WHERE CUST_ID = :CUST_ID1;
 UPDATE CUSTOMER SET "ORDER" = :ORDR1 WHERE CUST_ID = :CUST_ID2;
end ^

ALTER PROCEDURE UPDATE_CS_CUST_CONNECTION (XCS_ID INTEGER,
XCUST_ID INTEGER)
AS 
declare variable CS_ID INTEGER;
begin
  SELECT COUNT(*) FROM CUSTCS_LINK WHERE CS_ID = :XCS_ID INTO :CS_ID;
  IF( CS_ID = 0) THEN
   INSERT INTO CUSTCS_LINK(CS_ID, CUST_ID) VALUES(:XCS_ID, :XCUST_ID);
  ELSE
   UPDATE CUSTCS_LINK SET CUST_ID = :XCUST_ID WHERE CS_ID = :XCS_ID;
end ^

ALTER PROCEDURE UPDATE_ROWS_CINVOICE (XPRODUCT_ID INTEGER,
XINVOICE_ID INTEGER,
XQTY NUMERIC(9, 3))
AS 
declare variable QTY NUMERIC(9,3) ;
begin
  IF(XINVOICE_ID IS NULL) THEN
    SELECT FIRST 1 QTY FROM INVLINES WHERE PRODUCT_ID = :XPRODUCT_ID AND INVOICE_ID IS NULL INTO :QTY;
  ELSE
    SELECT FIRST 1 QTY FROM INVLINES WHERE PRODUCT_ID = :XPRODUCT_ID AND INVOICE_ID = :XINVOICE_ID INTO :QTY;

 IF(XQTY > 0) THEN
 BEGIN
  IF(QTY IS NOT NULL) then
  BEGIN
   IF(XINVOICE_ID IS NOT NULL) THEN
    UPDATE INVLINES SET QTY = :XQTY WHERE PRODUCT_ID = :XPRODUCT_ID AND INVOICE_ID = :XINVOICE_ID;
   ELSE
    UPDATE INVLINES SET QTY = :XQTY WHERE PRODUCT_ID = :XPRODUCT_ID AND INVOICE_ID IS NULL;
  END
  ELSE
  BEGIN
  INSERT INTO INVLINES(PRODUCT_ID, INVOICE_ID, QTY) VALUES(:XPRODUCT_ID, :XINVOICE_ID, :XQTY);
  END
 END
 ELSE
 BEGIN
  IF(XINVOICE_ID IS NOT NULL) THEN
   DELETE FROM INVLINES WHERE PRODUCT_ID = :XPRODUCT_ID AND INVOICE_ID = :XINVOICE_ID;
  ELSE
   DELETE FROM INVLINES WHERE PRODUCT_ID = :XPRODUCT_ID AND INVOICE_ID IS NULL;
 END

end ^

ALTER PROCEDURE YIELD_RETINV_STATS (SDEP_ID INTEGER)
RETURNS (INVTYPE_ID VARCHAR(6) CHARACTER SET WIN1253,
INVCODE_START VARCHAR(15) CHARACTER SET WIN1253,
INVCODE_END VARCHAR(15) CHARACTER SET WIN1253,
TOTAL_TRANSACTIONS CURRENCY)
AS 
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

/* Domain constraints */
ALTER DOMAIN PERCENTAGE ADD CONSTRAINT
         CHECK(VALUE BETWEEN 0 AND 100);
ALTER DOMAIN T_BOOLEAN ADD CONSTRAINT
         CHECK(VALUE BETWEEN 0 AND 1);
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER AUTO_INVOICE_LOG_BI FOR AUTO_INVOICE_LOG 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.LOG_ID IS NULL OR NEW.LOG_ID = 0) THEN
    NEW.LOG_ID = GEN_ID(GEN_AUTO_INVOICE_LOG_ID,1);
END ^

CREATE TRIGGER CUSTOMER_BI FOR CUSTOMER 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.CUST_ID IS NULL OR NEW.CUST_ID = 0) THEN
    NEW.CUST_ID = GEN_ID(GEN_CUSTOMER_ID,1);

  if (NEW.AFM IS NULL ) then
   NEW.AFM = NEW.CUST_ID;
END ^

CREATE TRIGGER DELIVERY_METHOD_BI FOR DELIVERY_METHOD 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.METHOD_ID IS NULL or (NEW.METHOD_ID = 0) ) THEN
    NEW.METHOD_ID = GEN_ID(GEN_DELIVERY_METHOD_ID,1);
END ^

CREATE TRIGGER DISTRIBUTION_AIM_BI FOR DISTRIBUTION_AIM 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.DISTAIM_ID IS NULL or (NEW.DISTAIM_ID = 0) ) THEN
    NEW.DISTAIM_ID = GEN_ID(GEN_DISTRIBUTION_AIM_ID,1);
END ^

CREATE TRIGGER INVLINES_BI FOR INVLINES 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.INVLINE_ID IS NULL or (NEW.INVLINE_ID = 0 ) ) THEN
    NEW.INVLINE_ID = GEN_ID(GEN_INVLINES_ID,1);



  SELECT NAME FROM METRIC_UNITS WHERE METRIC_ID = (SELECT METRIC_ID FROM PRODUCT WHERE PRODUCT_ID = NEW.PRODUCT_ID) INTO NEW.METRIC_UNIT;
END ^

CREATE TRIGGER INVLINES_AI FOR INVLINES 
ACTIVE AFTER INSERT POSITION 0 
as

begin
  DELETE FROM INVLINES WHERE PRODUCT_ID IS NULL;
end ^

CREATE TRIGGER INVLINES_BU FOR INVLINES 
ACTIVE BEFORE UPDATE POSITION 0 
as

begin

 SELECT NAME FROM METRIC_UNITS WHERE METRIC_ID = (SELECT METRIC_ID FROM PRODUCT WHERE PRODUCT_ID = NEW.PRODUCT_ID) INTO NEW.METRIC_UNIT;
end ^

CREATE TRIGGER INVLINES_AU FOR INVLINES 
ACTIVE AFTER UPDATE POSITION 0 
as
begin
    DELETE FROM INVLINES WHERE PRODUCT_ID IS NULL;
end ^

CREATE TRIGGER INVOICE_BI FOR INVOICE 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.INVOICE_ID IS NULL or (NEW.INVOICE_ID =0 ) ) THEN
    NEW.INVOICE_ID = GEN_ID(GEN_INVOICE_ID,1);
END ^

CREATE TRIGGER INVOICE_BI1 FOR INVOICE 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if(new.INVCODE is null) THEN
  begin
   select INV_CNTCODE FROM GET_INV_CODE(NEW.INVTYPE) INTO NEW.INVCODE ;
    SELECT INVTYPE.INVCOUNT FROM INVTYPE WHERE INVTYPE.INVTYPE_ID = NEW.INVTYPE INTO NEW.CODE;
  end
  SELECT INVTYPE.INVCOUNT FROM INVTYPE WHERE INVTYPE.INVTYPE_ID = NEW.INVTYPE INTO NEW.CODE;
end ^

CREATE TRIGGER INVOICE_AI FOR INVOICE 
ACTIVE AFTER INSERT POSITION 0 
as
declare variable INV_VALUE INTEGER;
begin
 SELECT INVCOUNT FROM INVTYPE WHERE INVTYPE.INVTYPE_ID = NEW.INVTYPE INTO :INV_VALUE;

 INV_VALUE = INV_VALUE +1;
 UPDATE INVTYPE SET INVCOUNT = :INV_VALUE WHERE INVTYPE.INVTYPE_ID = NEW.INVTYPE;
end ^

CREATE TRIGGER MARK_BI0 FOR MARK 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.ID IS NULL or new.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_MARK_ID,1);
END ^

CREATE TRIGGER MARK_AI0 FOR MARK 
ACTIVE AFTER INSERT OR UPDATE POSITION 0 
AS
begin
  IF(NEW.MYDATA_ACTION = 'INSERT') THEN
  BEGIN
    UPDATE INVOICE
    SET MYDATA_SENT = 1, MYDATA_STATE = 'VALID',
    MYDATA_MARK = NEW.MARK,
    MYDATA_URL = NEW.INVOICE_URL
    WHERE INVOICE.INVOICE_ID = NEW.INVOICE_ID;
  END
  ELSE IF(NEW.MYDATA_ACTION = 'CANCEL') THEN
  BEGIN
    UPDATE INVOICE
    SET MYDATA_SENT = 0,
    MYDATA_STATE = 'CANCELLED',
    MYDATA_MARK = NULL,
    MYDATA_URL = NULL
    WHERE INVOICE.INVOICE_ID = NEW.INVOICE_ID;
  END
end ^

CREATE TRIGGER METRIC_UNITS_BI FOR METRIC_UNITS 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.METRIC_ID IS NULL or (NEW.METRIC_ID = 0) ) THEN
    NEW.METRIC_ID = GEN_ID(GEN_METRIC_UNITS_ID,1);
END ^

CREATE TRIGGER PAYMENT_BI FOR PAYMENT 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.PAYMENT_ID IS NULL or (NEW.PAYMENT_ID = 0) ) THEN
    NEW.PAYMENT_ID = GEN_ID(GEN_PAYMENT_ID,1);
END ^

CREATE TRIGGER PAYMENT_METHOD_BI FOR PAYMENT_METHOD 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.METHOD_ID IS NULL or (NEW.METHOD_ID = 0) ) THEN
    NEW.METHOD_ID = GEN_ID(GEN_PAYMENT_METHOD_ID,1);
END ^

CREATE TRIGGER PRODUCT_BI FOR PRODUCT 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.product_id is null or (NEW.PRODUCT_ID = 0) ) then
    new.product_id = gen_id(gen_product_id,1);

end ^

CREATE TRIGGER PRODUCT_BI1 FOR PRODUCT 
ACTIVE BEFORE INSERT POSITION 1 
as
begin
  if(NEW.BARCODE IS NULL) then
   NEW.BARCODE = NEW.PRODUCT_ID;
end ^

CREATE TRIGGER PRODUCT_BU FOR PRODUCT 
ACTIVE BEFORE UPDATE POSITION 0 
as
begin
  new.LAST_UPDATE = 'NOW';
end ^

CREATE TRIGGER PRODUCT_CATEGORIES_BI FOR PRODUCT_CATEGORIES 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.cat_id is null or (NEW.CAT_ID = 0) ) then
    new.cat_id = gen_id(gen_product_categories_id,1);
end ^

CREATE TRIGGER PROD_PRICE_QTY_BI FOR PROD_PRICE_QTY 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.PROD_PRICE_ID IS NULL OR (NEW.PROD_PRICE_ID = 0) ) THEN
    NEW.PROD_PRICE_ID = GEN_ID(GEN_PROD_PRICE_QTY_ID,1);
END ^

CREATE TRIGGER REPORTS_BI FOR REPORTS 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.REPORT_ID IS NULL or new.report_id = 0) THEN
    NEW.REPORT_ID = GEN_ID(GEN_REPORTS_ID,1);
END ^

CREATE TRIGGER REPORT_INPUT_DATA_BI FOR REPORT_INPUT_DATA 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.INPUTDATA_ID IS NULL OR NEW.INPUTDATA_ID = 0) THEN
    NEW.INPUTDATA_ID = GEN_ID(GEN_REPORT_INPUT_DATA_ID,1);
END ^

CREATE TRIGGER VARTEXT_BI FOR VARTEXT 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.VARTEXT_ID IS NULL) THEN
    NEW.VARTEXT_ID = GEN_ID(GEN_VARTEXT_ID,1);
END ^

CREATE TRIGGER VAT_CATEGORY_BI FOR VAT_CATEGORY 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.vatcat_id is null or (NEW.VATCAT_ID=0) ) then
    new.vatcat_id = gen_id(gen_vat_category_id,1);
end ^

CREATE TRIGGER VAT_CATEGORY_AU0 FOR VAT_CATEGORY 
ACTIVE AFTER UPDATE POSITION 0 
AS
begin
 IF(NEW.default_cat = 1) THEN
 BEGIN
  UPDATE vat_category
  set VAT_CATEGORY.default_cat = 0
  WHERE vat_category.vatcat_id <> NEW.vatcat_id   ;
 END
end ^


SET TERM ; ^
COMMIT WORK;

/* Grant permissions for this database */
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON AUTO_INVOICE_LOG TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CONF_PARAMS TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CUSTCS_LINK TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CUSTOMER TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON CUSTOMER_CS_ACCEPTED TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DELIVERY_METHOD TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DISTRIBUTION_AIM TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON INVLINES TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON INVOICE TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON INVTYPE TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON MARK TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON METRIC_UNITS TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PAYMENT TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PAYMENT_METHOD TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PRODUCT TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PRODUCT_CATEGORIES TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PROD_PRICE_QTY TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON REPORTS TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON REPORT_INPUT_DATA TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON RETURN_INVOICE_EXTRAS TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON VARTEXT TO USER EKDOSI WITH GRANT OPTION;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON VAT_CATEGORY TO USER EKDOSI WITH GRANT OPTION;
GRANT RDB$ADMIN TO EKDOSI;
GRANT EXECUTE ON PROCEDURE CALCULATE_INVOICE_VALUES TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE CALCULATE_VAT_FOR_INVOICE TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE CHECK_PROD_AVAILABILITY TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE CREATE_RETURN_INVOICE TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE FILL_PRDESCR_INVLINES TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GET_ALL_CUSTOMERS_BALANCE TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GET_COMB_CUSTOMER_INVTYPES TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GET_COMB_INVLINES TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GET_COMB_INVOICES_CUSTOMERS TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GET_CUSTOMER_BALANCE TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE GET_INV_CODE TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE INSPECT_CUST_ORDER TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE LZ_PAD TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE SHOW_CUMULATIVE_INVOICE TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE SWAP_CUST_ORDER TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE UPDATE_CS_CUST_CONNECTION TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE UPDATE_ROWS_CINVOICE TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON PROCEDURE YIELD_RETINV_STATS TO USER EKDOSI WITH GRANT OPTION;
GRANT EXECUTE ON FUNCTION "lpad" TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_AUTO_INVOICE_LOG_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_CUSTOMER_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_DELIVERY_METHOD_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_DISTRIBUTION_AIM_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_INVLINES_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_INVOICE_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_INVPRLINES_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_MARK_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_METRIC_UNITS_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_PAYMENT_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_PAYMENT_METHOD_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_PRODUCT_CATEGORIES_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_PRODUCT_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_PROD_PRICE_QTY_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_REPORTS_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_REPORT_INPUT_DATA_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_VARTEXT_ID TO USER EKDOSI WITH GRANT OPTION;
GRANT USAGE ON SEQUENCE GEN_VAT_CATEGORY_ID TO USER EKDOSI WITH GRANT OPTION;

/* Comments for database objects. */
COMMENT ON DOMAIN       LONG_DESCRIPTION IS '';
COMMENT ON DOMAIN       T_AFM IS '';
COMMENT ON DOMAIN       T_BOOLEAN IS '';
COMMENT ON DOMAIN       T_DOC IS '';
COMMENT ON DOMAIN       T_VATNO IS 'AFM';
COMMENT ON    COLUMN    CUSTOMER.AFM IS '';
COMMENT ON    COLUMN    CUSTOMER."ORDER" IS '';
COMMENT ON TABLE        DELIVERY_METHOD IS '';
COMMENT ON TABLE        INVLINES IS '';
COMMENT ON    COLUMN    INVOICE.DISCOUNT IS '';
COMMENT ON    COLUMN    INVTYPE.DISTAIM_ID IS '';
COMMENT ON    COLUMN    INVTYPE.DELIVERYMETHOD_ID IS '';
COMMENT ON    COLUMN    INVTYPE.PAYMETH_ID IS '';
COMMENT ON    COLUMN    INVTYPE.CREDITINVOICE IS '';
COMMENT ON    COLUMN    INVTYPE.RETURNINVOICE IS '';
COMMENT ON TABLE        METRIC_UNITS IS '';
COMMENT ON TABLE        PAYMENT_METHOD IS '';
COMMENT ON    COLUMN    PAYMENT_METHOD.DUE_DAYS IS '';
COMMENT ON    COLUMN    PRODUCT.PRODUCT_ID IS '';
COMMENT ON    COLUMN    PRODUCT.BARCODE IS '';
COMMENT ON    COLUMN    PRODUCT.DESCRIPTION_SHORT IS '';
COMMENT ON    COLUMN    PRODUCT.CAT_ID IS '';
COMMENT ON    COLUMN    PRODUCT.VATCAT_ID IS '';
COMMENT ON    COLUMN    PRODUCT.BUY_PRICE IS '';
COMMENT ON    COLUMN    PRODUCT.SELL_PRICE IS '';
COMMENT ON    COLUMN    PRODUCT.PRICE_WVAT IS '';
COMMENT ON    COLUMN    PRODUCT.DATE_INSERTED IS '';
COMMENT ON    COLUMN    PRODUCT.RESERVE IS '';
COMMENT ON    COLUMN    PRODUCT.RESERVE_SECURE IS '';
COMMENT ON    COLUMN    PRODUCT.DESCRIPTION IS '';
COMMENT ON    COLUMN    REPORT_INPUT_DATA.VARIABLE_NAME IS '';
COMMENT ON    COLUMN    REPORT_INPUT_DATA.VAL IS '';
COMMENT ON PROCEDURE    FILL_PRDESCR_INVLINES IS '';
COMMENT ON PROCEDURE    INSPECT_CUST_ORDER IS '';
COMMENT ON PROCEDURE    UPDATE_ROWS_CINVOICE IS '';
